If you're using Django 4.2+, you can enable the exception autocapture integration which will also automatically capture Django errors.

```python
from posthog import Posthog
from posthog.exception_capture import Integrations

Posthog("<ph_project_api_key>", enable_exception_autocapture=True, exception_autocapture_integrations = [Integrations.Django])
```

For older versions of Django, you will need to instrument your views individually:

``` python
# urls.py
handler404 = 'mysite.views.custom_not_found_view'

# views.py
from django.http import HttpResponseNotFound
from posthog import capture_exception

def custom_not_found_view(*args, **kwargs):
    capture_exception("Page not found!")
    return HttpResponseNotFound("Not found")
```