### Setting up Python exception autocapture

> **Note:** A minimum SDK version of v3.7.0 is required, but we recommend keeping up to date with the latest version to ensure you have all of error tracking's features.

Exception autocapture can be enabled during initialization of the PostHog client to automatically capture any unhandled exceptions thrown by your Python application. It works by setting Python's built-in exception hooks, such as `sys.excepthook` and `threading.excepthook`.

```python
from posthog import Posthog

posthog = Posthog("<ph_project_api_key>", enable_exception_autocapture=True, ...)
```

We also recommend setting up and using [contexts](/docs/libraries/python#contexts) so that exceptions automatically include distinct IDs, session IDs, and other properties you can set up with tags.

### Capturing errors in Python frameworks

Python frameworks often have built-in error handlers. This means PostHog’s default exception autocapture won’t work and we need to manually capture errors instead. The exact process for doing this depends on the framework:

import Tab from "components/Tab"
import DjangoContextMiddleware from '../../libraries/python/_snippets/django-context-middleware.mdx'
import PythonFlaskExceptionAutocapture from './python-flask-exception-autocapture.mdx'
import PythonFastAPIExceptionAutocapture from './python-fastapi-exception-autocapture.mdx'

<Tab.Group tabs={['Django', 'Flask', 'FastAPI']}>
    <Tab.List>
      <Tab>Django</Tab>
      <Tab>Flask</Tab>
      <Tab>FastAPI</Tab>
    </Tab.List>
    <Tab.Panels>
        <Tab.Panel>
            <DjangoContextMiddleware />
        </Tab.Panel>
        <Tab.Panel>
            <PythonFlaskExceptionAutocapture />
        </Tab.Panel>
        <Tab.Panel>
            <PythonFastAPIExceptionAutocapture />
        </Tab.Panel>
    </Tab.Panels>
</Tab.Group>

### Manually capturing exceptions in Python

For exceptions handled by your application that you would still like sent to PostHog, you can manually call the capture method:

```python
posthog.capture_exception(e, properties=additional_properties)
```

You can find a full example of all of this in our [Python (and Flask) error tracking tutorial](/tutorials/python-error-tracking).
